In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10)

In [3]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1[1]

1

In [6]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1[-2:]

array([8, 9])

In [12]:
#NumPy arrays differ from python lists because of their ability to broadcast
#Broadcast = setting a value with index range
arr1[0:2]=100
arr1

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
#array slicing is not a copy. it's a reference to prevend memory issues
arr1 = np.arange(10)
slice1 = arr1[0:5]
slice1[:]=100

In [19]:
slice1

array([100, 100, 100, 100, 100])

In [20]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [21]:
#if you want to copy data, you have to be explicit
arr2 = np.arange(10)
slice2 = arr2.copy()

In [22]:
slice2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
slice2[:]=200
slice2

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [26]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Indexing 2-D arrays
arr_2d = np.array([[5,10,15] , [20,25,30] , [35,40,45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[1][0]

20

In [31]:
#2-D slicing
#2x2 up-right corner [[10,15],[25,35]]
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
#Select using comparison operators
arr3 = np.arange(1,11)

In [34]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr3>2

array([False, False,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [36]:
arr3[arr3>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr3.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
arr3[arr3>4]

array([ 5,  6,  7,  8,  9, 10])