In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3]

In [3]:
lst

[1, 2, 3]

In [4]:
np.array(lst)

array([1, 2, 3])

In [5]:
matrix = [[1,2,3] , [4,5,6] , [7,8,9]]

In [6]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#generate array via range

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
#generate arrays of zeros
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [12]:
#Attention for 2-dim put inner ()
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
#generate arrays of ones
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [14]:
#Attention to 2-dim, put inner ()
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [15]:
#eye = identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [16]:
#random.rand  creates array with random values between 0-1
np.random.rand(2,5)

array([[ 0.31192911,  0.33084328,  0.95094056,  0.28831869,  0.12542749],
       [ 0.51495278,  0.63340795,  0.63987512,  0.71353037,  0.97173341]])

In [18]:
#random.randint  creates array with random integers between a range
randint_array1 = np.random.randint(1,100,10)

In [19]:
randint_array1

array([47,  6, 68, 22, 98, 98,  7, 99, 66, 87])

In [21]:
randint_array1.max()

99

In [22]:
randint_array1.min()

6

In [24]:
#argmax() = index location of max
randint_array1.argmax()

7

In [27]:
#shape =  shape of the array (dimensions)
randint_array1.shape #attribute not method, that's why no ()

(10L,)

In [28]:
array2 = np.random.rand(2,3)

In [29]:
array2.shape

(2L, 3L)

In [30]:
array2

array([[ 0.63259982,  0.4933249 ,  0.26326854],
       [ 0.72024148,  0.45869056,  0.68113998]])

In [31]:
#dtype = data type
array2.dtype

dtype('float64')

In [32]:
randint_array1.dtype

dtype('int32')